# Generated by Django 3.0.2 on 2020-01-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=30)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=20)),
                ('Zipcode', models.IntegerField()),
                ('Country', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
