# Generated by Django 3.0.2 on 2020-01-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='slug',
        ),
    ]
