# Generated by Django 3.0.2 on 2020-01-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_personaldata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='Name',
            field=models.CharField(max_length=30),
        ),
    ]
