# Generated by Django 3.0.2 on 2020-01-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Excel',
            field=models.FileField(upload_to='excel/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='Html',
            field=models.FileField(upload_to='html/'),
        ),
    ]
