# Generated by Django 3.0.2 on 2020-01-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200118_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='Subject',
            field=models.CharField(default='Sample', max_length=200),
        ),
    ]
