# Generated by Django 3.0.2 on 2020-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_files_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='Html',
            field=models.FileField(upload_to='templates/'),
        ),
    ]
